---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_get_query_param__pageSize"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings?pageSize=INFO:"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions: []
tags:
- "V1"
authors:
- "FX Bot"
category: null
severity: null
inactive: false
policies: null
